# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: dev-local
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true # we use Grunt + BrowserSync for livereload
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        #url: jdbc:mysql://ec2-54-255-148-73.ap-southeast-1.compute.amazonaws.com:3306/Taskman?useUnicode=true&characterEncoding=utf8
        url: jdbc:mysql://localhost:3306/TaskMan?useUnicode=true&characterEncoding=utf8
        name:
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show_sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: true
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: smtp.gmail.com
        port: 587
        username: timesheettestuser1@gmail.com
        password: Test123#
        properties:
            mail.transport.protocol: smtp
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.port: 587
            mail.debug: true

    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

liquibase:
    contexts: dev
    enabled: false

server:
    port: 8088

upload:
    file:
         path: /opt/uploads
export:
    file:
         path: /opt/exports
qrcode:
    file:
         path: /opt/qrcode
attendance:
    shiftStartLeadTime: 1
    shiftEndLeadTime: 1
    shiftStartGraceTime: 1
    shiftEndGraceTime: 1
    file:
        path:  /opt/attendance
    template:
        path: /opt/template/Attendance_Report_Format.xlsx    
quotation:
    file:
        path:  /opt/quotation
ticket:
    file:
        path:  /opt/ticket        
import:
    file:
        path:
            new: /opt/imports/new
            completed: /opt/imports/completed
asset:
   file:
       path: D:\asset\uploads\site      
   weekly:
       template:
           path: /opt/template/Asset_52Week_Report_Format.xlsx
multipart:
   maxFileSize: 15MB
   maxRequestSize: 15MB
         
max:
    user: 10
    userGroup: 2
    device: 30

email:
    notification:
        overdue: true
        eodReports: true
        enabled: true
#        schedule1: 0 0 9 * * ?
#        schedule2: 0 0 18 * * ?
        url: http://localhost:8088/
    activation:
        title: Account activation
    reset:
        title: Account password reset
    report:
        title: Job reports
    overdue:
        report:
            title: Overdue job report
    compleed:
        report:
            title: Completed job report

reports:
    job-report:
        url: http://localhost:8088/#/job-reports
    attendance-report:
        url: http://localhost:8088/#/attendance-reports
    asset-report:
        url: http://localhost:8088/#/asset-report

url:
    ticket-view: http://localhost:8088/#/view-ticket
    quotation-view: http://localhost:8088/#/view-quotation
    
facedetection:
    api:
        url: https://api.kairos.com/detect
        enrollUrl: https://api.kairos.com/enroll
        verifyUrl: https://api.kairos.com/verify
        apiKey: a6ae8363069107177e06c3ca3f76a66b
        apiId: 2f2877f2

locationService:
#   url: http://locahost:8000/api/site/location
#   url: http://ec2-52-77-216-21.ap-southeast-1.compute.amazonaws.com:8000/api/site/location
   url: http://ec2-54-169-225-123.ap-southeast-1.compute.amazonaws.com:8000/api/site/location

quotationService:
#   url: http://locahost:8000/api/site/location
#   url: http://ec2-52-77-216-21.ap-southeast-1.compute.amazonaws.com:8000/api/site/location
   url: http://ec2-54-169-225-123.ap-southeast-1.compute.amazonaws.com:8001/api

pushService:
   url: http://localhost:9000/
   
AWS:
   s3-url: https://s3.ap-south-1.amazonaws.com
   s3-accessKey: AKIAJJQEB7US7QOAV2LQ 
   s3-secretKey: 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
   s3-bucketName: fms-taskman
   s3-cloudfront-url: http://d1wn8hrsdttztl.cloudfront.net/
   s3-bucketEnv: dev/
   s3-asset-path: assets/
   s3-qrcode-path: qrcode/
   s3-attendance-path: attendance/
   s3-ticket-path : tickets/
   s3-quotation-path : quotations/

scheduler:
   job:
      creationPolicy: monthly
   dailyJob:
      enabled: true
      creation: monthly
   weeklyJob:
      enabled: true
   monthlyJob:
      enabled: true
   yearlyJob:
      enabled: true
      creation: daily
   fortnightlyJob:
      enabled: true
      creation: daily
   halfyearlyJob:
      enabled: true
      creation: yearly
   overdueJob:
      enabled: false
   eodJobReport:
      enabled: true
   attendanceDetailReport:
      enabled: true
   attendanceConsolidatedReport:
      enabled: true

default.user.password: uds12345

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 256M
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: no-reply@taskman.uds.com
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: TimeSheet
