package com.ts.app.domain;

/**
 * Created by karth on 7/1/2017.
 */
public enum AssetStatus {
//    OPEN,ASSIGNED,INPROGRESS,COMPLETED,OVERDUE,OUTOFSCOPE
	COMMISSIONED,IN_USE,UNDER_MAINTENANCE,UNDER_REPAIR,STOLEN,MISSING,DE_COMMISSIONED,DISPOSED,RETIRED

}
