//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:01:31 AM IST 
//


package com.ts.app.soap.classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soap.wsdl.api.employee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soap.wsdl.api.employee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZempdetailUpdate }
     * 
     */
    public ZempdetailUpdate createZempdetailUpdate() {
        return new ZempdetailUpdate();
    }

    /**
     * Create an instance of {@link TableOfZempDetStr }
     * 
     */
    public TableOfZempDetStr createTableOfZempDetStr() {
        return new TableOfZempDetStr();
    }

    /**
     * Create an instance of {@link TableOfZempEduDet }
     * 
     */
    public TableOfZempEduDet createTableOfZempEduDet() {
        return new TableOfZempEduDet();
    }

    /**
     * Create an instance of {@link TableOfZempFamilyDet }
     * 
     */
    public TableOfZempFamilyDet createTableOfZempFamilyDet() {
        return new TableOfZempFamilyDet();
    }

    /**
     * Create an instance of {@link TableOfZempIdsStr }
     * 
     */
    public TableOfZempIdsStr createTableOfZempIdsStr() {
        return new TableOfZempIdsStr();
    }

    /**
     * Create an instance of {@link TableOfZempIdmarkDet }
     * 
     */
    public TableOfZempIdmarkDet createTableOfZempIdmarkDet() {
        return new TableOfZempIdmarkDet();
    }

    /**
     * Create an instance of {@link TableOfZempPfnominiDet }
     * 
     */
    public TableOfZempPfnominiDet createTableOfZempPfnominiDet() {
        return new TableOfZempPfnominiDet();
    }

    /**
     * Create an instance of {@link TableOfZempPrevempDet }
     * 
     */
    public TableOfZempPrevempDet createTableOfZempPrevempDet() {
        return new TableOfZempPrevempDet();
    }

    /**
     * Create an instance of {@link TableOfZempReturn }
     * 
     */
    public TableOfZempReturn createTableOfZempReturn() {
        return new TableOfZempReturn();
    }

    /**
     * Create an instance of {@link ZempdetailUpdateResponse }
     * 
     */
    public ZempdetailUpdateResponse createZempdetailUpdateResponse() {
        return new ZempdetailUpdateResponse();
    }

    /**
     * Create an instance of {@link ZempDetStr }
     * 
     */
    public ZempDetStr createZempDetStr() {
        return new ZempDetStr();
    }

    /**
     * Create an instance of {@link ZempEduDet }
     * 
     */
    public ZempEduDet createZempEduDet() {
        return new ZempEduDet();
    }

    /**
     * Create an instance of {@link ZempFamilyDet }
     * 
     */
    public ZempFamilyDet createZempFamilyDet() {
        return new ZempFamilyDet();
    }

    /**
     * Create an instance of {@link ZempIdsStr }
     * 
     */
    public ZempIdsStr createZempIdsStr() {
        return new ZempIdsStr();
    }

    /**
     * Create an instance of {@link ZempIdmarkDet }
     * 
     */
    public ZempIdmarkDet createZempIdmarkDet() {
        return new ZempIdmarkDet();
    }

    /**
     * Create an instance of {@link ZempPfnominiDet }
     * 
     */
    public ZempPfnominiDet createZempPfnominiDet() {
        return new ZempPfnominiDet();
    }

    /**
     * Create an instance of {@link ZempPrevempDet }
     * 
     */
    public ZempPrevempDet createZempPrevempDet() {
        return new ZempPrevempDet();
    }

    /**
     * Create an instance of {@link ZempReturn }
     * 
     */
    public ZempReturn createZempReturn() {
        return new ZempReturn();
    }

}
