//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:01:31 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:sap-com:document:sap:soap:functions:mc-style")
package com.ts.app.soap.classes;
