//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:01:31 AM IST 
//


package com.ts.app.soap.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZempIdmarkDet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZempIdmarkDet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmpId" type="{urn:sap-com:document:sap:rfc:functions}numeric8"/&gt;
 *         &lt;element name="IdenmarkId" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="IdenmarkText" type="{urn:sap-com:document:sap:rfc:functions}char100"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZempIdmarkDet", propOrder = {
    "empId",
    "idenmarkId",
    "idenmarkText"
})
public class ZempIdmarkDet {

    @XmlElement(name = "EmpId", required = true)
    protected String empId;
    @XmlElement(name = "IdenmarkId", required = true)
    protected String idenmarkId;
    @XmlElement(name = "IdenmarkText", required = true)
    protected String idenmarkText;

    /**
     * Gets the value of the empId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpId(String value) {
        this.empId = value;
    }

    /**
     * Gets the value of the idenmarkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdenmarkId() {
        return idenmarkId;
    }

    /**
     * Sets the value of the idenmarkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdenmarkId(String value) {
        this.idenmarkId = value;
    }

    /**
     * Gets the value of the idenmarkText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdenmarkText() {
        return idenmarkText;
    }

    /**
     * Sets the value of the idenmarkText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdenmarkText(String value) {
        this.idenmarkText = value;
    }

}
