//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:01:31 AM IST 
//


package com.ts.app.soap.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZempFamilyDet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZempFamilyDet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmpId" type="{urn:sap-com:document:sap:rfc:functions}numeric8"/&gt;
 *         &lt;element name="FamMemName" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="FamMemDob" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="FamMemRelNo" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZempFamilyDet", propOrder = {
    "empId",
    "famMemName",
    "famMemDob",
    "famMemRelNo"
})
public class ZempFamilyDet {

    @XmlElement(name = "EmpId", required = true)
    protected String empId;
    @XmlElement(name = "FamMemName", required = true)
    protected String famMemName;
    @XmlElement(name = "FamMemDob", required = true)
    protected String famMemDob;
    @XmlElement(name = "FamMemRelNo", required = true)
    protected String famMemRelNo;

    /**
     * Gets the value of the empId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpId(String value) {
        this.empId = value;
    }

    /**
     * Gets the value of the famMemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamMemName() {
        return famMemName;
    }

    /**
     * Sets the value of the famMemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamMemName(String value) {
        this.famMemName = value;
    }

    /**
     * Gets the value of the famMemDob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamMemDob() {
        return famMemDob;
    }

    /**
     * Sets the value of the famMemDob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamMemDob(String value) {
        this.famMemDob = value;
    }

    /**
     * Gets the value of the famMemRelNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamMemRelNo() {
        return famMemRelNo;
    }

    /**
     * Sets the value of the famMemRelNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamMemRelNo(String value) {
        this.famMemRelNo = value;
    }

}
