//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:01:31 AM IST 
//


package com.ts.app.soap.classes;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZempPfnominiDet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZempPfnominiDet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmpId" type="{urn:sap-com:document:sap:rfc:functions}numeric8"/&gt;
 *         &lt;element name="NominiName" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="NominiRel" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="NominiPercen" type="{urn:sap-com:document:sap:rfc:functions}decimal5.2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZempPfnominiDet", propOrder = {
    "empId",
    "nominiName",
    "nominiRel",
    "nominiPercen"
})
public class ZempPfnominiDet {

    @XmlElement(name = "EmpId", required = true)
    protected String empId;
    @XmlElement(name = "NominiName", required = true)
    protected String nominiName;
    @XmlElement(name = "NominiRel", required = true)
    protected String nominiRel;
    @XmlElement(name = "NominiPercen", required = true)
    protected BigDecimal nominiPercen;

    /**
     * Gets the value of the empId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpId(String value) {
        this.empId = value;
    }

    /**
     * Gets the value of the nominiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNominiName() {
        return nominiName;
    }

    /**
     * Sets the value of the nominiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNominiName(String value) {
        this.nominiName = value;
    }

    /**
     * Gets the value of the nominiRel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNominiRel() {
        return nominiRel;
    }

    /**
     * Sets the value of the nominiRel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNominiRel(String value) {
        this.nominiRel = value;
    }

    /**
     * Gets the value of the nominiPercen property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNominiPercen() {
        return nominiPercen;
    }

    /**
     * Sets the value of the nominiPercen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNominiPercen(BigDecimal value) {
        this.nominiPercen = value;
    }

}
