//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:01:31 AM IST 
//


package com.ts.app.soap.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmpDet" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempDetStr"/&gt;
 *         &lt;element name="EmpEduDet" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempEduDet"/&gt;
 *         &lt;element name="EmpFamilyDet" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempFamilyDet"/&gt;
 *         &lt;element name="EmpIdentityProof" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempIdsStr"/&gt;
 *         &lt;element name="EmpIdmarkDet" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempIdmarkDet"/&gt;
 *         &lt;element name="EmpPfnominiDet" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempPfnominiDet"/&gt;
 *         &lt;element name="EmpPrevempDet" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempPrevempDet"/&gt;
 *         &lt;element name="ErrorFlag" type="{urn:sap-com:document:sap:rfc:functions}char200"/&gt;
 *         &lt;element name="ReturnLog" type="{urn:sap-com:document:sap:soap:functions:mc-style}TableOfZempReturn"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "empDet",
    "empEduDet",
    "empFamilyDet",
    "empIdentityProof",
    "empIdmarkDet",
    "empPfnominiDet",
    "empPrevempDet",
    "errorFlag",
    "returnLog"
})
@XmlRootElement(name = "ZempdetailUpdateResponse")
public class ZempdetailUpdateResponse {

    @XmlElement(name = "EmpDet", required = true)
    protected TableOfZempDetStr empDet;
    @XmlElement(name = "EmpEduDet", required = true)
    protected TableOfZempEduDet empEduDet;
    @XmlElement(name = "EmpFamilyDet", required = true)
    protected TableOfZempFamilyDet empFamilyDet;
    @XmlElement(name = "EmpIdentityProof", required = true)
    protected TableOfZempIdsStr empIdentityProof;
    @XmlElement(name = "EmpIdmarkDet", required = true)
    protected TableOfZempIdmarkDet empIdmarkDet;
    @XmlElement(name = "EmpPfnominiDet", required = true)
    protected TableOfZempPfnominiDet empPfnominiDet;
    @XmlElement(name = "EmpPrevempDet", required = true)
    protected TableOfZempPrevempDet empPrevempDet;
    @XmlElement(name = "ErrorFlag", required = true)
    protected String errorFlag;
    @XmlElement(name = "ReturnLog", required = true)
    protected TableOfZempReturn returnLog;

    /**
     * Gets the value of the empDet property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempDetStr }
     *     
     */
    public TableOfZempDetStr getEmpDet() {
        return empDet;
    }

    /**
     * Sets the value of the empDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempDetStr }
     *     
     */
    public void setEmpDet(TableOfZempDetStr value) {
        this.empDet = value;
    }

    /**
     * Gets the value of the empEduDet property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempEduDet }
     *     
     */
    public TableOfZempEduDet getEmpEduDet() {
        return empEduDet;
    }

    /**
     * Sets the value of the empEduDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempEduDet }
     *     
     */
    public void setEmpEduDet(TableOfZempEduDet value) {
        this.empEduDet = value;
    }

    /**
     * Gets the value of the empFamilyDet property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempFamilyDet }
     *     
     */
    public TableOfZempFamilyDet getEmpFamilyDet() {
        return empFamilyDet;
    }

    /**
     * Sets the value of the empFamilyDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempFamilyDet }
     *     
     */
    public void setEmpFamilyDet(TableOfZempFamilyDet value) {
        this.empFamilyDet = value;
    }

    /**
     * Gets the value of the empIdentityProof property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempIdsStr }
     *     
     */
    public TableOfZempIdsStr getEmpIdentityProof() {
        return empIdentityProof;
    }

    /**
     * Sets the value of the empIdentityProof property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempIdsStr }
     *     
     */
    public void setEmpIdentityProof(TableOfZempIdsStr value) {
        this.empIdentityProof = value;
    }

    /**
     * Gets the value of the empIdmarkDet property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempIdmarkDet }
     *     
     */
    public TableOfZempIdmarkDet getEmpIdmarkDet() {
        return empIdmarkDet;
    }

    /**
     * Sets the value of the empIdmarkDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempIdmarkDet }
     *     
     */
    public void setEmpIdmarkDet(TableOfZempIdmarkDet value) {
        this.empIdmarkDet = value;
    }

    /**
     * Gets the value of the empPfnominiDet property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempPfnominiDet }
     *     
     */
    public TableOfZempPfnominiDet getEmpPfnominiDet() {
        return empPfnominiDet;
    }

    /**
     * Sets the value of the empPfnominiDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempPfnominiDet }
     *     
     */
    public void setEmpPfnominiDet(TableOfZempPfnominiDet value) {
        this.empPfnominiDet = value;
    }

    /**
     * Gets the value of the empPrevempDet property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempPrevempDet }
     *     
     */
    public TableOfZempPrevempDet getEmpPrevempDet() {
        return empPrevempDet;
    }

    /**
     * Sets the value of the empPrevempDet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempPrevempDet }
     *     
     */
    public void setEmpPrevempDet(TableOfZempPrevempDet value) {
        this.empPrevempDet = value;
    }

    /**
     * Gets the value of the errorFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorFlag() {
        return errorFlag;
    }

    /**
     * Sets the value of the errorFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorFlag(String value) {
        this.errorFlag = value;
    }

    /**
     * Gets the value of the returnLog property.
     * 
     * @return
     *     possible object is
     *     {@link TableOfZempReturn }
     *     
     */
    public TableOfZempReturn getReturnLog() {
        return returnLog;
    }

    /**
     * Sets the value of the returnLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableOfZempReturn }
     *     
     */
    public void setReturnLog(TableOfZempReturn value) {
        this.returnLog = value;
    }

}
