//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 01:01:31 AM IST 
//


package com.ts.app.soap.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZempDetStr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZempDetStr"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmpId" type="{urn:sap-com:document:sap:rfc:functions}numeric8"/&gt;
 *         &lt;element name="EmployeeType" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="EmpName" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="Gender" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="MaritalStatus" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="MothersName" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="DateOfBirth" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="BloodGroup" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="Religion" type="{urn:sap-com:document:sap:rfc:functions}char15"/&gt;
 *         &lt;element name="EsiNo" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="DesigNo" type="{urn:sap-com:document:sap:rfc:functions}numeric8"/&gt;
 *         &lt;element name="DesigTxt" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="PfNo" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="DateOfJoin" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="HouseNum1M" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="StreetM" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="AddrLi2M" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="DistrictM" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="CityM" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="StateM" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="PinM" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TelResM" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *         &lt;element name="MobileNoM" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="Email" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="HouseNum1P" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="StreetP" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="AddrLi2P" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="DistrictP" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="CityP" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="StateP" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *         &lt;element name="PinP" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="TelResP" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *         &lt;element name="AcNo" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="BankName" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="BankBranch" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="BankKey" type="{urn:sap-com:document:sap:rfc:functions}char15"/&gt;
 *         &lt;element name="IfscCode" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="Persa" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="EmerContNo" type="{urn:sap-com:document:sap:rfc:functions}char14"/&gt;
 *         &lt;element name="ZreferPer" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="Wbs" type="{urn:sap-com:document:sap:rfc:functions}char24"/&gt;
 *         &lt;element name="Activity" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="Caste" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="DisabilityId" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZempDetStr", propOrder = {
    "empId",
    "employeeType",
    "empName",
    "gender",
    "maritalStatus",
    "mothersName",
    "dateOfBirth",
    "bloodGroup",
    "religion",
    "esiNo",
    "desigNo",
    "desigTxt",
    "pfNo",
    "dateOfJoin",
    "houseNum1M",
    "streetM",
    "addrLi2M",
    "districtM",
    "cityM",
    "stateM",
    "pinM",
    "telResM",
    "mobileNoM",
    "email",
    "houseNum1P",
    "streetP",
    "addrLi2P",
    "districtP",
    "cityP",
    "stateP",
    "pinP",
    "telResP",
    "acNo",
    "bankName",
    "bankBranch",
    "bankKey",
    "ifscCode",
    "persa",
    "emerContNo",
    "zreferPer",
    "wbs",
    "activity",
    "caste",
    "disabilityId"
})
public class ZempDetStr {

    @XmlElement(name = "EmpId", required = true)
    protected String empId;
    @XmlElement(name = "EmployeeType", required = true)
    protected String employeeType;
    @XmlElement(name = "EmpName", required = true)
    protected String empName;
    @XmlElement(name = "Gender", required = true)
    protected String gender;
    @XmlElement(name = "MaritalStatus", required = true)
    protected String maritalStatus;
    @XmlElement(name = "MothersName", required = true)
    protected String mothersName;
    @XmlElement(name = "DateOfBirth", required = true)
    protected String dateOfBirth;
    @XmlElement(name = "BloodGroup", required = true)
    protected String bloodGroup;
    @XmlElement(name = "Religion", required = true)
    protected String religion;
    @XmlElement(name = "EsiNo", required = true)
    protected String esiNo;
    @XmlElement(name = "DesigNo", required = true)
    protected String desigNo;
    @XmlElement(name = "DesigTxt", required = true)
    protected String desigTxt;
    @XmlElement(name = "PfNo", required = true)
    protected String pfNo;
    @XmlElement(name = "DateOfJoin", required = true)
    protected String dateOfJoin;
    @XmlElement(name = "HouseNum1M", required = true)
    protected String houseNum1M;
    @XmlElement(name = "StreetM", required = true)
    protected String streetM;
    @XmlElement(name = "AddrLi2M", required = true)
    protected String addrLi2M;
    @XmlElement(name = "DistrictM", required = true)
    protected String districtM;
    @XmlElement(name = "CityM", required = true)
    protected String cityM;
    @XmlElement(name = "StateM", required = true)
    protected String stateM;
    @XmlElement(name = "PinM", required = true)
    protected String pinM;
    @XmlElement(name = "TelResM", required = true)
    protected String telResM;
    @XmlElement(name = "MobileNoM", required = true)
    protected String mobileNoM;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "HouseNum1P", required = true)
    protected String houseNum1P;
    @XmlElement(name = "StreetP", required = true)
    protected String streetP;
    @XmlElement(name = "AddrLi2P", required = true)
    protected String addrLi2P;
    @XmlElement(name = "DistrictP", required = true)
    protected String districtP;
    @XmlElement(name = "CityP", required = true)
    protected String cityP;
    @XmlElement(name = "StateP", required = true)
    protected String stateP;
    @XmlElement(name = "PinP", required = true)
    protected String pinP;
    @XmlElement(name = "TelResP", required = true)
    protected String telResP;
    @XmlElement(name = "AcNo", required = true)
    protected String acNo;
    @XmlElement(name = "BankName", required = true)
    protected String bankName;
    @XmlElement(name = "BankBranch", required = true)
    protected String bankBranch;
    @XmlElement(name = "BankKey", required = true)
    protected String bankKey;
    @XmlElement(name = "IfscCode", required = true)
    protected String ifscCode;
    @XmlElement(name = "Persa", required = true)
    protected String persa;
    @XmlElement(name = "EmerContNo", required = true)
    protected String emerContNo;
    @XmlElement(name = "ZreferPer", required = true)
    protected String zreferPer;
    @XmlElement(name = "Wbs", required = true)
    protected String wbs;
    @XmlElement(name = "Activity", required = true)
    protected String activity;
    @XmlElement(name = "Caste", required = true)
    protected String caste;
    @XmlElement(name = "DisabilityId", required = true)
    protected String disabilityId;

    /**
     * Gets the value of the empId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpId(String value) {
        this.empId = value;
    }

    /**
     * Gets the value of the employeeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeType() {
        return employeeType;
    }

    /**
     * Sets the value of the employeeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeType(String value) {
        this.employeeType = value;
    }

    /**
     * Gets the value of the empName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * Sets the value of the empName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpName(String value) {
        this.empName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the mothersName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMothersName() {
        return mothersName;
    }

    /**
     * Sets the value of the mothersName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMothersName(String value) {
        this.mothersName = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the bloodGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloodGroup() {
        return bloodGroup;
    }

    /**
     * Sets the value of the bloodGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloodGroup(String value) {
        this.bloodGroup = value;
    }

    /**
     * Gets the value of the religion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReligion() {
        return religion;
    }

    /**
     * Sets the value of the religion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReligion(String value) {
        this.religion = value;
    }

    /**
     * Gets the value of the esiNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsiNo() {
        return esiNo;
    }

    /**
     * Sets the value of the esiNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsiNo(String value) {
        this.esiNo = value;
    }

    /**
     * Gets the value of the desigNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesigNo() {
        return desigNo;
    }

    /**
     * Sets the value of the desigNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesigNo(String value) {
        this.desigNo = value;
    }

    /**
     * Gets the value of the desigTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesigTxt() {
        return desigTxt;
    }

    /**
     * Sets the value of the desigTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesigTxt(String value) {
        this.desigTxt = value;
    }

    /**
     * Gets the value of the pfNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPfNo() {
        return pfNo;
    }

    /**
     * Sets the value of the pfNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPfNo(String value) {
        this.pfNo = value;
    }

    /**
     * Gets the value of the dateOfJoin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfJoin() {
        return dateOfJoin;
    }

    /**
     * Sets the value of the dateOfJoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfJoin(String value) {
        this.dateOfJoin = value;
    }

    /**
     * Gets the value of the houseNum1M property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNum1M() {
        return houseNum1M;
    }

    /**
     * Sets the value of the houseNum1M property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNum1M(String value) {
        this.houseNum1M = value;
    }

    /**
     * Gets the value of the streetM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetM() {
        return streetM;
    }

    /**
     * Sets the value of the streetM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetM(String value) {
        this.streetM = value;
    }

    /**
     * Gets the value of the addrLi2M property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLi2M() {
        return addrLi2M;
    }

    /**
     * Sets the value of the addrLi2M property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLi2M(String value) {
        this.addrLi2M = value;
    }

    /**
     * Gets the value of the districtM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictM() {
        return districtM;
    }

    /**
     * Sets the value of the districtM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictM(String value) {
        this.districtM = value;
    }

    /**
     * Gets the value of the cityM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityM() {
        return cityM;
    }

    /**
     * Sets the value of the cityM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityM(String value) {
        this.cityM = value;
    }

    /**
     * Gets the value of the stateM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateM() {
        return stateM;
    }

    /**
     * Sets the value of the stateM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateM(String value) {
        this.stateM = value;
    }

    /**
     * Gets the value of the pinM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinM() {
        return pinM;
    }

    /**
     * Sets the value of the pinM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinM(String value) {
        this.pinM = value;
    }

    /**
     * Gets the value of the telResM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelResM() {
        return telResM;
    }

    /**
     * Sets the value of the telResM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelResM(String value) {
        this.telResM = value;
    }

    /**
     * Gets the value of the mobileNoM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNoM() {
        return mobileNoM;
    }

    /**
     * Sets the value of the mobileNoM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNoM(String value) {
        this.mobileNoM = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the houseNum1P property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNum1P() {
        return houseNum1P;
    }

    /**
     * Sets the value of the houseNum1P property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNum1P(String value) {
        this.houseNum1P = value;
    }

    /**
     * Gets the value of the streetP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetP() {
        return streetP;
    }

    /**
     * Sets the value of the streetP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetP(String value) {
        this.streetP = value;
    }

    /**
     * Gets the value of the addrLi2P property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLi2P() {
        return addrLi2P;
    }

    /**
     * Sets the value of the addrLi2P property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLi2P(String value) {
        this.addrLi2P = value;
    }

    /**
     * Gets the value of the districtP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictP() {
        return districtP;
    }

    /**
     * Sets the value of the districtP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictP(String value) {
        this.districtP = value;
    }

    /**
     * Gets the value of the cityP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityP() {
        return cityP;
    }

    /**
     * Sets the value of the cityP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityP(String value) {
        this.cityP = value;
    }

    /**
     * Gets the value of the stateP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateP() {
        return stateP;
    }

    /**
     * Sets the value of the stateP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateP(String value) {
        this.stateP = value;
    }

    /**
     * Gets the value of the pinP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinP() {
        return pinP;
    }

    /**
     * Sets the value of the pinP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinP(String value) {
        this.pinP = value;
    }

    /**
     * Gets the value of the telResP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelResP() {
        return telResP;
    }

    /**
     * Sets the value of the telResP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelResP(String value) {
        this.telResP = value;
    }

    /**
     * Gets the value of the acNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcNo() {
        return acNo;
    }

    /**
     * Sets the value of the acNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcNo(String value) {
        this.acNo = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the bankBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * Sets the value of the bankBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankBranch(String value) {
        this.bankBranch = value;
    }

    /**
     * Gets the value of the bankKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankKey() {
        return bankKey;
    }

    /**
     * Sets the value of the bankKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankKey(String value) {
        this.bankKey = value;
    }

    /**
     * Gets the value of the ifscCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfscCode() {
        return ifscCode;
    }

    /**
     * Sets the value of the ifscCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfscCode(String value) {
        this.ifscCode = value;
    }

    /**
     * Gets the value of the persa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersa() {
        return persa;
    }

    /**
     * Sets the value of the persa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersa(String value) {
        this.persa = value;
    }

    /**
     * Gets the value of the emerContNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmerContNo() {
        return emerContNo;
    }

    /**
     * Sets the value of the emerContNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmerContNo(String value) {
        this.emerContNo = value;
    }

    /**
     * Gets the value of the zreferPer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZreferPer() {
        return zreferPer;
    }

    /**
     * Sets the value of the zreferPer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZreferPer(String value) {
        this.zreferPer = value;
    }

    /**
     * Gets the value of the wbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWbs() {
        return wbs;
    }

    /**
     * Sets the value of the wbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWbs(String value) {
        this.wbs = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivity(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the caste property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaste() {
        return caste;
    }

    /**
     * Sets the value of the caste property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaste(String value) {
        this.caste = value;
    }

    /**
     * Gets the value of the disabilityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisabilityId() {
        return disabilityId;
    }

    /**
     * Sets the value of the disabilityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisabilityId(String value) {
        this.disabilityId = value;
    }

}
